# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/AXIS_SUB/AXIS_SUB.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXIS_SUB || ORIG_REF_NAME==AXIS_SUB} -quiet] -quiet

# IP: bd/AXIS_SUB/ip/AXIS_SUB_axis_control_0_0/AXIS_SUB_axis_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXIS_SUB_axis_control_0_0 || ORIG_REF_NAME==AXIS_SUB_axis_control_0_0} -quiet] -quiet

# IP: bd/AXIS_SUB/ip/AXIS_SUB_c_addsub_0_0/AXIS_SUB_c_addsub_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXIS_SUB_c_addsub_0_0 || ORIG_REF_NAME==AXIS_SUB_c_addsub_0_0} -quiet] -quiet

# XDC: bd/AXIS_SUB/AXIS_SUB_ooc.xdc
