######################################################################
#
# File name : AXIS_SUB_TB_simulate.do
# Created on: Mon Jan 13 21:33:14 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L xbip_utils_v3_0_9 -L c_reg_fd_v12_0_5 -L xbip_dsp48_wrapper_v3_0_4 -L xbip_pipe_v3_0_5 -L xbip_dsp48_addsub_v3_0_5 -L xbip_addsub_v3_0_5 -L c_addsub_v12_0_12 -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.AXIS_SUB_TB xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {AXIS_SUB_TB_wave.do}

view wave
view structure
view signals

do {AXIS_SUB_TB.udo}

run 1000ns
