######################################################################
#
# File name : AXIS_SUB_TB_wave.do
# Created on: Mon Jan 13 21:33:14 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
